series:
  enabled: true
  name: Турецкие
  src: y:\Mamul
  dest: f:\Турецкие

editorial_video:
  enabled: true
  name: Редакция
  src: e:\Storage\Редакция
  dest: f:\Редакция

series_map:
  - src: Muhtemel Ask.s01.WEB-DLRip720p
    dest: Возможная любовь
  - src: Haysiyet.s01.WEB-DLRip1080p
    dest: Достоинство
  - src: Daha 17
    dest: Ещё 17
  - src: Kizilcik Serbeti.s05.WEB-DLRip1080p
    dest: Кизиловый щербет
  - src: Mercan Kosk.s01.WEB-DLRip1080p
    dest: Коралловый дворец
  - src: Ask ve Taht.s01.WEB-DLRip1080p
    dest: Любовь и трон
  - src: Gunesin Dogdugu Yer.s01.WEB-DLRip1080p
    dest: Место, где восходит солнце
  - src: Tuzlu Kahve.s01.WEB-DLRip1080p
    dest: Солёный кофе
  - src: Sevdan Bir Atest.s01.WEB-DLRip1080p
    dest: Твоя любовь - огонь
